[package]
name = "pallet-evm"
version = "6.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/frontier/"
description = "FRAME EVM contracts pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types = { version = "0.10.0", default-features = false, features = ["rlp", "byteorder"] }
sha3 = { version = "0.8", default-features = false }
log = { version = "0.4", default-features = false }
hex = { version = "0.4", default-features = false }
rlp = { version = "0.5", default-features = false }

# substrate
sp-io = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-core = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-balances = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-timestamp = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false, optional = true }

# frontier
fp-evm = { version = "3.0.0-dev", default-features = false, path = "../../primitives/evm" }
evm = { version = "0.30.1", path = "../../vendor/evm", default-features = false, features = ["with-codec"] }
evm-runtime = { version = "0.30.0", path = "../../vendor/evm/runtime", default-features = false }
evm-gasometer = { version = "0.30.0", path = "../../vendor/evm/gasometer" ,default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"primitive-types/std",
	"sha3/std",
	"log/std",
	"hex/std",
	"rlp/std",

	"sp-io/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"pallet-balances/std",
	"pallet-timestamp/std",
	"frame-support/std",
	"frame-system/std",

	"fp-evm/std",
	"evm/std",
	"evm/with-serde",
	"evm-runtime/std",
	"evm-gasometer/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
]
